// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egfqwqgihmozczbhuxil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZnF3cWdpaG1vemN6Ymh1eGlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTk2OTAsImV4cCI6MjA2MzczNTY5MH0.eYwlnH-1ICAKOCRTuE44cYoTlHEyneJZTIreVthNpEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);